In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

In [32]:
df = pd.read_csv("multivariate_homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [35]:
#handling nan value
import math
median_value = math.floor(df.bedrooms.median())
median_value

4

In [36]:
df.bedrooms = df.bedrooms.fillna(median_value)

In [37]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [44]:
#creating object of linear regression
reg = linear_model.LinearRegression()
#training model with reg object
reg.fit(df[['age','bedrooms','area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [47]:
reg.coef_


array([-3231.71790863, 23388.88007794,   112.06244194])

In [48]:
reg.intercept_

221323.00186539633

In [52]:
#predicting price incase of age bedroom and area
reg.predict([[10,1.0,3000]])

array([548582.02868342])

In [53]:
#predicting price incase of age bedroom and area
reg.predict([[20,1.0,3000]])

array([516264.84959709])